apiVersion: v1
kind: ConfigMap
metadata:
  name: tremligeiro-production-config
  namespace: tremligeiro
data:
  ENV: "dev"
  PORT: "8080"
  POSTGRES_DB: "tremligeiro_production_db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "admintremligeiro"
  POSTGRES_HOST: "tremligeiro-postgres-db-production.cdnilrkxgmpa.us-east-1.rds.amazonaws.com"
  ORDER_TOPIC_ARN: "arn:aws:sns:us-east-1:000047597454:ProductionTopic"
  PRODUCTION_ORDER_QUEUE_URL: "https://sqs.us-east-1.amazonaws.com/000047597454/OrderQueueAppProduction" 
  AWS_REGION: "us-east-1"
  AWS_USE_CREDENTIALS: "true"