apiVersion: v1
kind: Secret
metadata:
  name: tremligeiro-production-secret
  namespace: tremligeiro
  labels:
    app: tremligeiro-production
    environment: "dev"
type: Opaque
data:
  POSTGRES_PASS: YWRtaW50cmVtbGlnZWlybw==
  PAYMENT_AUTH_TOKEN: VEVTVC0xNDgwMjA1NTI0NDkwMzU0LTAxMTYyMS00MjE5YzVkZGZmZDgzMTkyYmJhMmEwMjMxNGExNDAxZi0yMDI5Nzg3MDY=
  AWS_ACCESS_KEY_ID: ASIAWVOVB6M2X45IVUDU
  AWS_SECRET_ACCESS_KEY: uWYKBXm6HLBAYJJ5iSIk3VPrvJV0BzLWXEPz4Ez2
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEPf//////////wEaCXVzLXdlc3QtMiJIMEYCIQDrtKyN2qAzkX9Mlujcegz8X/bPvFLVjOmzgvHOIt7osgIhAN2SRfaY+oLiz4+mvxHs+7vAcO7Uxij/e1rLQPP403crKrUCCLD//////////wEQARoMNDU4Mzk3NzA5MTA5Igw2gAqAP+dv8l2WgpoqiQKp/fW47fFHLJdR9eqg0ek91HhpTuOKl044oYx1sL2pEvtphR8zGPaq1kk5onRGcFwcz0Qjm1YSJGw5GyeWWvpi3i1lTL15HAIQgmrDYC0E6Xr127PT02ajJM8/G5wxGzHVao9ikzQ15taBeGKJezKqNS9M4zeIuPFDZsQsL0sqq7AVVsr9pOzLu9bjwOIgWS4pDXKiOSfoDlq8vQhTmW/qwF/NBypXYEVUxJdJkgy9ekP30yoosDpE5NjKVYC14ec98pvWcieysCq8TFSVRb8YTABrnU9lKtRs2C684Gq3vmrrDdQZFw9LOmeGA+Ik8Ld0yf+weqbnNxH3s4sSSO/OiVpL+k3TQOUCMPqJtMEGOpwBBTb/A0Cw6hovcgFOZ7VcbrGiTX96Gx5+6l3ipYpSuzRrbGW3AnZKotemeRrod41V91t6+WUEOx7/Y8d9u5+6NdAcRICRGjFhTP4fRvScC07ZHn61phg0MIvEKR+B9HEb0uBGq83j+3Wtuxue/qQe/kWh2ItwAM7DF3q91YAJj+jbOOnYtz2R7gKMbw/Pixw0lP8vl6h/bj5du1iB