apiVersion: v1
kind: Secret
metadata:
  name: tremligeiro-production-secret
  namespace: tremligeiro
  labels:
    app: tremligeiro-production
    environment: "dev"
type: Opaque
data:
  POSTGRES_PASS: YWRtaW50cmVtbGlnZWlybw==
  PAYMENT_AUTH_TOKEN: VEVTVC0xNDgwMjA1NTI0NDkwMzU0LTAxMTYyMS00MjE5YzVkZGZmZDgzMTkyYmJhMmEwMjMxNGExNDAxZi0yMDI5Nzg3MDY=
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""
  