apiVersion: v1
kind: Secret
metadata:
  name: tremligeiro-production-secret
  namespace: tremligeiro
  labels:
    app: tremligeiro-production
    environment: "dev"
type: Opaque
data:
  POSTGRES_PASS: YWRtaW50cmVtbGlnZWlybw==
  PAYMENT_AUTH_TOKEN: VEVTVC0xNDgwMjA1NTI0NDkwMzU0LTAxMTYyMS00MjE5YzVkZGZmZDgzMTkyYmJhMmEwMjMxNGExNDAxZi0yMDI5Nzg3MDY=
  AWS_ACCESS_KEY_ID: "QVNJQVFBQVdXSTZIR1RWSENGUkI="
  AWS_SECRET_ACCESS_KEY: "NzA2bzMrd29qZnJSdGQxWXhrTXJIdjJGckZmRDNIbWN2S0o4ejdXdw=="
  AWS_SESSION_TOKEN: "SVFvSmIzSnBaMmx1WDJWakVQbi8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpITUVVQ0lGZnR0QXZjSzY4ZXc5ODluZmdZSjNwNTcyclNpUHZRNm9STUh5b2syaUU5QWlFQXZtVkxLcDd2ajB1Mkc3TWN1QW9zcXMramNxY2pLSUllOW1iWW9Vc1FWM1FxdFFJSXN2Ly8vLy8vLy8vL0FSQUJHZ3d3TURBd05EYzFPVGMwTlRRaUREUUg2Wmg2dGZZT216NGNNaXFKQWozdTlIV0o4amkvc2t0MVFkRGYwUWcwd3puY0JuNE0yZ1R2QjF2cDRxRE5kOE5udW9Vc0VWaHJMRVpVR2tRS01hV0g4b1RNVk1PTm5LcXk0UFN4bXRsSEFnY3MzQjMwN0dMZzF0R0g5cDRUUW4rV0R1L1U4ZE5vcnc1MzZuSmIzMlN6YXpPMGRjY3RvbUFCb3pHcVdGZDAwWitGSXBGVFlZNzJJN013QWY1cFBYNnJOblAxV0xuenRwM3drZk5XRFhwd3VZbXdsNlBRUFowd2JTcU1ieTg5RzBKQjNMSEZRK0I0djE2V2NudTg4eHRmdnZ2UDZQUmViTXhoMk5tWjdDeXlwb0RzS2kyTVJydEpBTGRkQlIyNlRHL0drUll4V0tzL2IxQUNHMjRRVUVKRkJXdUVCY1dqQWpleXd0RE42UzJzVlVDS1RYb0FoL3kyKzk0SmZ0Z005c1lURERBUnIzQXczODYwd1FZNm5nR1JKdFNBK3B5a0c5MmNwNzNzYkdYd0N6N0ZVbElpT1Z3SnpkQUJVaVFqaWY4amRuNG9LakdreWxPTWx1K3FRUFZmRjdGa1ZIQ0FRYVM0Q0QzSHJRR2tDRlNKdTZhTHl1WVEzS2plWVc2UWpMV280Uzd3bjE5cVpWSE1ueTFBMk0xb3pmejl6Nkx3OW9HTWF0a1d5ZGp2NTlJdzlMQkZiNjNucjJ3S1RWcGtIN2tZOVlSMDZISTc2Qko5VEV2ZTRDaWlCRkU3akQyejYxaWphd0Q0ckE9PQ=="
  